-- =========================================================
-- NOVA LUXE PostgreSQL Seed Data
-- 24 Curated Products in INR (₹) + Categories + Promo Codes
-- =========================================================

-- 1. Insert Categories
INSERT INTO categories (id, name, slug, icon) VALUES
('electronics', 'Electronics & Gear', 'electronics', 'cpu'),
('audio', 'Pro Audio & Sound', 'audio', 'headphones'),
('fashion', 'Street Fashion & Footwear', 'fashion', 'shopping-bag'),
('lifestyle', 'Home & Modern Living', 'lifestyle', 'home')
ON CONFLICT (id) DO NOTHING;

-- 2. Insert Coupons
INSERT INTO coupons (code, discount_type, discount_value, min_order_amount, description, is_active) VALUES
('WELCOME10', 'percent', 10.00, 500.00, '10% OFF on first order above ₹500', TRUE),
('SAVE20', 'percent', 20.00, 2000.00, '20% OFF on premium orders above ₹2,000', TRUE),
('FESTIVE500', 'flat', 500.00, 3000.00, 'Flat ₹500 OFF on festive orders above ₹3,000', TRUE)
ON CONFLICT (code) DO NOTHING;

-- 3. Insert 24 Curated Products (INR ₹)
INSERT INTO products (id, name, brand, category_id, price, original_price, rating, reviews_count, badge, image_url, description, features, in_stock, is_trending, stock_quantity) VALUES
(
    'prod-01',
    'Aura Pro Active Noise Cancelling Headphones',
    'AuraSound',
    'audio',
    12999.00,
    19999.00,
    4.9,
    1840,
    'Best Seller',
    'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
    'Immersive sound with studio-grade spatial audio, hybrid active noise cancellation, and ultra-plush memory foam cushions for 40 hours of playtime.',
    '["Hybrid 4-Mic Active Noise Cancellation", "40-Hour Battery Life with Fast Charge (10m = 5h)", "Custom 40mm Titanium Dynamic Drivers", "Bluetooth 5.3 with Multipoint Pairing"]'::jsonb,
    TRUE,
    TRUE,
    45
),
(
    'prod-02',
    'NeoTitanium Ultra Smartwatch Gen 4',
    'Chronos',
    'electronics',
    8499.00,
    14999.00,
    4.8,
    950,
    'Trending',
    'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
    'Aerospace-grade titanium frame with always-on AMOLED sapphire display, ECG tracking, Bluetooth calling, and 12-day battery life.',
    '["1.43\" Vivid AMOLED with 1000 nits brightness", "Continuous SpO2, Heart Rate & Stress Monitor", "IP68 Waterproof & 5ATM Swim Resistance", "100+ Sports Modes & GPS Multi-satellite"]'::jsonb,
    TRUE,
    TRUE,
    60
),
(
    'prod-03',
    'NovaPulse Mechanical Gaming Keyboard',
    'NovaTech',
    'electronics',
    4999.00,
    7999.00,
    4.7,
    620,
    'Popular',
    'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
    'Compact 75% hot-swappable mechanical keyboard with lubricated linear switches, per-key RGB lighting, and gasket-mounted dampening sound.',
    '["Gasket Mount with 5-Layer Acoustic Foam", "Hot-Swappable 5-Pin Switch Sockets", "Tri-Mode Wireless (2.4G/BT 5.0/Type-C)", "Double-shot PBT Keycaps with shine-through"]'::jsonb,
    TRUE,
    FALSE,
    30
),
(
    'prod-04',
    'UrbanStride Minimalist Street Sneakers',
    'Veloce',
    'fashion',
    3499.00,
    5999.00,
    4.6,
    840,
    'Hot Deal',
    'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&auto=format&fit=crop&q=80',
    'Ultra-lightweight ergonomic sneakers crafted with breathable knit mesh, cloud-foam shock-absorbing sole, and modern streetwear aesthetic.',
    '["SuperCloud Responsive Cushioning Sole", "Breathable Eco-Recycled Knit Fabric", "Anti-Odor Memory Foam Insole", "Slip-Resistant Textured Rubber Outsole"]'::jsonb,
    TRUE,
    TRUE,
    80
),
(
    'prod-05',
    'ZenAmbient Smart Hydroponic Herb Garden',
    'ZenHome',
    'lifestyle',
    6299.00,
    8999.00,
    4.8,
    310,
    'Eco Pick',
    'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800&auto=format&fit=crop&q=80',
    'Indoor smart garden with automated LED grow lighting, whisper-quiet self-watering circulation, and nutrient alarm. Fresh greens all year.',
    '["Full-Spectrum Automated 24W Grow Light", "Smart Water Level & Nutrient Reminders", "Grows 6 Plants Simultaneously 5x Faster", "BPA-Free, Clean & Zero-Soil Hydroponics"]'::jsonb,
    TRUE,
    FALSE,
    25
),
(
    'prod-06',
    'SonicBlast Portable Rugged Speaker',
    'BoomCore',
    'audio',
    2999.00,
    4999.00,
    4.7,
    1120,
    'Best Value',
    'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&auto=format&fit=crop&q=80',
    'Punchy 360-degree bass with IP67 dust and waterproof armor, 24-hour battery reserve, and dynamic party RGB illumination rings.',
    '["30W Deep Bass Output with Dual Passive Radiators", "IP67 Dustproof, Sandproof & Float in Water", "PartySync Link: Pair up to 100+ Speakers", "Built-in Power Bank to charge your mobile"]'::jsonb,
    TRUE,
    TRUE,
    55
),
(
    'prod-07',
    'SpectraCraft Ergonomic Task Chair',
    'ErgoMaster',
    'lifestyle',
    11499.00,
    16999.00,
    4.9,
    480,
    'Top Rated',
    'https://images.unsplash.com/photo-1580481077195-c3a821a58875?w=800&auto=format&fit=crop&q=80',
    'Engineered for all-day focus. High-density Korean mesh backrest, adaptive lumbar support, 3D armrests, and 135-degree recline lock.',
    '["Dynamic Self-Adjusting Lumbar Cradle", "CoolWeave Breathable German Mesh Fabric", "Class 4 Heavy Duty Heavy-Load Gas Lift", "Silent Polyurethane Rollerblade Casters"]'::jsonb,
    TRUE,
    FALSE,
    20
),
(
    'prod-08',
    'LuxeVoyage Water-Resistant Tech Backpack',
    'NomadGear',
    'fashion',
    2799.00,
    4499.00,
    4.7,
    780,
    'Popular',
    'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
    'Sleek 28L anti-theft commuter backpack with TSA-approved 16" padded laptop vault, USB charging passthrough, and waterproof ballistic nylon.',
    '["Water-Repellent 900D Oxford Ballistic Shell", "Dedicated Shockproof 16\" Laptop Compartment", "Hidden Anti-Theft RFID Shielded Pocket", "Luggage Trolley Strap & External USB Port"]'::jsonb,
    TRUE,
    TRUE,
    70
),
(
    'prod-09',
    'ClarityLens 4K Studio Streaming Webcam',
    'VisionPro',
    'electronics',
    5999.00,
    8999.00,
    4.6,
    430,
    'Creator Pick',
    'https://images.unsplash.com/photo-1588702547923-7093a6c3ba33?w=800&auto=format&fit=crop&q=80',
    'Ultra HD 4K 60FPS video sensor with AI autofocus, dual noise-cancelling microphones, and magnetic privacy shutter.',
    '["Sony STARVIS CMOS Sensor with HDR", "Intelligent Face-Tracking & Dual Stereo Mic", "Adjustable Field of View (65°, 78°, 90°)", "Plug and Play with USB-C 3.1 Interface"]'::jsonb,
    TRUE,
    FALSE,
    40
),
(
    'prod-10',
    'AromaZen Ultrasonic Essential Oil Diffuser',
    'ZenHome',
    'lifestyle',
    1899.00,
    2999.00,
    4.8,
    610,
    'Relaxation',
    'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&auto=format&fit=crop&q=80',
    'Handcrafted ceramic ultrasonic diffuser with ambient candlelight glow, 500ml reservoir, and whisper-quiet operation.',
    '["500ml Capacity: 16 Hours Continuous Mist", "Waterless Auto Shut-Off Safety Feature", "7 Calming Ambient LED Color Cycles", "Ultra-Fine 2.4MHz Cool Mist Technology"]'::jsonb,
    TRUE,
    FALSE,
    50
),
(
    'prod-11',
    'ApexPro Magnetic Wireless PowerBank 10000mAh',
    'VoltGrid',
    'electronics',
    2499.00,
    3999.00,
    4.7,
    920,
    'Essential',
    'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=800&auto=format&fit=crop&q=80',
    'Snap-and-charge magnetic wireless power bank with 22.5W Power Delivery fast charging, foldable kickstand, and digital battery LED indicator.',
    '["Strong 12N Snap-to-Charge Magnetic Alignment", "22.5W Fast Charging via USB-C PD", "Foldable Zinc Alloy Kickstand for Video Viewing", "Multi-protection Safety Shield Against Overheating"]'::jsonb,
    TRUE,
    TRUE,
    90
),
(
    'prod-12',
    'Solaris Polarized Aviator Sunglasses',
    'SolLux',
    'fashion',
    1999.00,
    3499.00,
    4.5,
    540,
    'Summer Drop',
    'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&auto=format&fit=crop&q=80',
    'Ultra-lightweight stainless steel frame with UV400 multi-layer polarized TAC lenses to eliminate glare and enhance true colors.',
    '["100% UV400 Anti-Glare Polarized Lenses", "Corrosion-Resistant Surgical Steel Frame", "Soft Silicone Nose Pads with Zero Pinching", "Includes Leather Hard Case & Microfiber Cloth"]'::jsonb,
    TRUE,
    FALSE,
    65
),
(
    'prod-13',
    'PulseFlow True Wireless Earbuds with ANC',
    'AuraSound',
    'audio',
    3999.00,
    6999.00,
    4.8,
    1450,
    'Hot Deal',
    'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
    'Zero-latency gaming mode, 32dB active noise cancellation, IPX5 sweat resistance, and 36-hour total battery case.',
    '["32dB Hybrid Active Noise Cancellation", "Super Low Latency 40ms Gaming Mode", "Wireless Qi Fast Charging Case", "Quad-Mic Environmental Noise Cancellation for Calls"]'::jsonb,
    TRUE,
    TRUE,
    110
),
(
    'prod-14',
    'NeoGlow Ambient Smart Desk Light Bar',
    'NovaTech',
    'lifestyle',
    2699.00,
    4299.00,
    4.7,
    390,
    'Trending',
    'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&auto=format&fit=crop&q=80',
    'Screen-mounted anti-glare light bar with wireless desktop dial, auto-dimming brightness sensor, and dual-tone RGB backlighting.',
    '["Zero Screen Reflection Asymmetrical Optical Design", "Wireless 2.4GHz Rotary Controller Dial", "Step-less Color Temperature Adjustment (2700K - 6500K)", "Ambient RGB Backlight for Gaming Immersion"]'::jsonb,
    TRUE,
    FALSE,
    35
),
(
    'prod-15',
    'AeroGlide Wireless Ergonomic Vertical Mouse',
    'ErgoMaster',
    'electronics',
    2199.00,
    3499.00,
    4.6,
    520,
    'Ergo Pick',
    'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80',
    '57-degree vertical handshake angle eliminates wrist strain. 4000 DPI silent optical tracking, thumb rest, and rechargeable battery.',
    '["Scientific 57° Natural Handshake Posture", "Whisper-Quiet Click Mechanism (90% Noise Reduction)", "Tri-Device Connectivity (Bluetooth + 2.4G)", "USB-C Rechargeable with 4-Month Battery Life"]'::jsonb,
    TRUE,
    FALSE,
    45
),
(
    'prod-16',
    'HyperBreeze Portable Turbo Desk Fan',
    'ZenHome',
    'lifestyle',
    1499.00,
    2499.00,
    4.6,
    380,
    'Popular',
    'https://images.unsplash.com/photo-1618941716939-553df3c6c278?w=800&auto=format&fit=crop&q=80',
    'Brushless turbo aerodynamics with whisper-quiet airflow, oscillating head, 4000mAh lithium battery for 12 hours cordless operation.',
    '["Jet-Engine Inspired Aerodynamic Blades", "Ultra Quiet 20dB Brushless Motor", "120° Automatic Wide-Angle Oscillation", "Type-C Fast Charging 4000mAh Battery"]'::jsonb,
    TRUE,
    FALSE,
    60
),
(
    'prod-17',
    'TitanShield Rugged Military Smartwatch',
    'Chronos',
    'electronics',
    5999.00,
    9999.00,
    4.8,
    410,
    'Heavy Duty',
    'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80',
    'Military-grade MIL-STD-810H shockproof watch with built-in dual-beam flashlight, compass, altimeter, and 20-day battery.',
    '["Certified MIL-STD-810H Shock & Impact Proof", "Built-in Ultra Bright Dual LED Flashlight", "Compass, Altimeter & Barometer Sensors", "Corning Gorilla Glass Anti-Scratch Lens"]'::jsonb,
    TRUE,
    TRUE,
    35
),
(
    'prod-18',
    'StudioMaster Reference Wireless Headphones',
    'AuraSound',
    'audio',
    16999.00,
    24999.00,
    4.9,
    670,
    'Audiophile',
    'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80',
    'Audiophile-grade planar magnetic open-back headphones engineered for lossless high-resolution monitoring with balanced audio.',
    '["Planar Magnetic Transducers for Pure Clarity", "Real Walnut Wood Earcups & Lambskin Pads", "Hi-Res Audio Certified with LDAC & aptX HD", "Detachable Braided Silver-Plated OFC Cable"]'::jsonb,
    TRUE,
    FALSE,
    15
),
(
    'prod-19',
    'Zenith Carbon Fiber Minimalist Cardholder Wallet',
    'NomadGear',
    'fashion',
    1499.00,
    2499.00,
    4.7,
    890,
    'EDC Pick',
    'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&auto=format&fit=crop&q=80',
    'Aerospace 3K matte carbon fiber with RFID blocking shield, integrated elastic cash strap, and quick-flick card access mechanism.',
    '["Full RFID/NFC Skimming Protection", "Holds up to 12 Cards plus Folded Cash", "Aircraft-Grade Aluminum Inner Chamber", "Ultra-Slim 6mm Profile for Front Pocket"]'::jsonb,
    TRUE,
    TRUE,
    120
),
(
    'prod-20',
    'PureAura Smart HEPA Air Purifier Pro',
    'ZenHome',
    'lifestyle',
    7999.00,
    11999.00,
    4.8,
    520,
    'Health',
    'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&auto=format&fit=crop&q=80',
    'True H13 HEPA filtration removes 99.97% of smoke, dust, and PM2.5 pollutants. Smart laser air quality sensor with real-time numeric display.',
    '["Medical-Grade True H13 HEPA Filter", "Real-Time Laser PM2.5 Air Quality Index Display", "Whisper-Quiet 24dB Sleep Mode", "Covers up to 500 Sq. Ft. Room in 15 Mins"]'::jsonb,
    TRUE,
    TRUE,
    28
),
(
    'prod-21',
    'RetroGlow RGB Nixie Tube Desk Clock',
    'NovaTech',
    'lifestyle',
    3499.00,
    5499.00,
    4.9,
    230,
    'Limited Drop',
    'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=800&auto=format&fit=crop&q=80',
    'Modern simulation of vintage Soviet nixie tubes with 16-million customizable IPS RGB glow displays and magnetic dust cover.',
    '["6x Full Color Customizable IPS Glow Displays", "Wi-Fi NTP Clock Sync for Atomic Precision", "Solid Anodized Aluminum Alloy Base", "Over 20 Dynamic Animation & Audio Visualizer Modes"]'::jsonb,
    TRUE,
    FALSE,
    18
),
(
    'prod-22',
    'Phantom Glide Wireless Charging Gaming Mousepad',
    'NovaTech',
    'electronics',
    1999.00,
    3299.00,
    4.6,
    740,
    'Gaming',
    'https://images.unsplash.com/photo-1616440347437-b1c73416efc2?w=800&auto=format&fit=crop&q=80',
    'Extra-large micro-textured control surface with built-in 15W fast wireless charging zone for your phone or wireless mouse.',
    '["Integrated 15W Qi Fast Wireless Charging Coil", "Micro-Woven Low-Friction Speed Surface", "360° Edge-Lit Custom RGB Spectrum Lighting", "Non-Slip Textured Natural Rubber Base"]'::jsonb,
    TRUE,
    FALSE,
    55
),
(
    'prod-23',
    'CloudShift Premium Oversized Street Hoodie',
    'Veloce',
    'fashion',
    2499.00,
    3999.00,
    4.7,
    630,
    'Trending',
    'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80',
    '450 GSM French terry heavyweight cotton with double-layered hood, dropped shoulders, and embroidered minimalist typography.',
    '["Heavyweight 450 GSM 100% Combed Cotton", "Pre-Shrunk Fade-Resistant Reactive Dye", "Deep Hidden Kangaroo Pocket with Zipper", "Ribbed Cuffs & Hem with Reinforced Stitching"]'::jsonb,
    TRUE,
    TRUE,
    95
),
(
    'prod-24',
    'TerraGrip Insulated Stainless Steel Flask 1000ml',
    'NomadGear',
    'lifestyle',
    1299.00,
    1999.00,
    4.8,
    1100,
    'Best Seller',
    'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&auto=format&fit=crop&q=80',
    'Double-wall vacuum insulation keeps liquids icy cold for 24 hours or piping hot for 12 hours. Powder-coated 18/8 food-grade steel.',
    '["24-Hour Cold & 12-Hour Hot Vacuum Core", "100% Leak-Proof Magnetic Chug Lid", "Durable Textured Powder-Coat Finish", "BPA-Free, Zero Condensation & Zero Sweat"]'::jsonb,
    TRUE,
    FALSE,
    140
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category_id = EXCLUDED.category_id,
    price = EXCLUDED.price,
    original_price = EXCLUDED.original_price,
    rating = EXCLUDED.rating,
    reviews_count = EXCLUDED.reviews_count,
    badge = EXCLUDED.badge,
    image_url = EXCLUDED.image_url,
    description = EXCLUDED.description,
    features = EXCLUDED.features,
    in_stock = EXCLUDED.in_stock,
    is_trending = EXCLUDED.is_trending,
    stock_quantity = EXCLUDED.stock_quantity;
